### ISSUE TITLE
Not all inputs have been set

### ISSUE THREAD

**Issue by YoungZBang** [socathie/keras2circom#6]
Hello. I attempted to run the example you provided and got a circuit.circom and a circuit.json file. But I found the number of input signals in circuit.json is different from the number needed by circuits.circom. So i got the following error when generating witness.

Not all inputs have been set. Only 1074 out of 17155
circuit: main.cpp:278: int main(int, char**): Assertion `false' failed.
Aborted (core dumped)

**Comment by socathie** [comment]
Hi, circuit.json is not the entire input.json because it includes just the model weights. You will need to construct your own input and include it in the json file for circuit input.
